[rdbms]
  [rdbms.database]
  name = "sample_db"
  port = 5432
  [rdbms.user]
  name = "sakthivel"
  password = "admin123"


[servers]

  # You can indent as you please. Tabs or spaces. TOML don't care.
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"
